package it.polimi.ingsw.model.utils;

public enum GameParameter {
    NOF_PLAYERS,
    MOTHERNATURE_INCREMENT,
    PLAYER_ORDER,
    ASSISTCARD_INDEX,
    PLAYER_ID,
    THREE_STUDENTS_INDEXES,
    STUDENT_INDEXES,
    THREE_STUDENTS_PLACES,
    ISLAND_INDEX,
    ISLAND_INDEXES,
    CLOUD_INDEX,
    CHARACTER_CARD_INDEX
}
